name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

  api-test:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run server in background
      run: |
        dotnet run --project server/ &  # Kör din API-server i bakgrunden
        sleep 10  # Vänta lite för att låta servern starta

    - name: Install Node.js (for Newman)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman API tests
      run: |
        newman run server/tests/crm-test.postman_collection.json \
          --environment server/tests/crm-test.postman_environment.json \
          --insecure \
          --reporters cli

  gui-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Restore GUI test project
        run: dotnet restore ServerGuiTests

      - name: Build GUI test project
        run: dotnet build ServerGuiTests

      - name: Install browsers
        run: playwright install

      - name: Run Playwright GUI tests
        run: dotnet test ServerGuiTests
